- name: Network Getting Started First Playbook
  hosts: gitlab-runner
  tasks:
    - name: download images
      docker_image:
        name: "gitlab/gitlab-runner:latest"
        state: present
    - name: run the runner
      command: |
        docker run -d --rm --name gitlab-runner \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v /home/gitlab-runner:/home/gitlab-runner \
          -v /buiilds:/builds --privileged \
          gitlab/gitlab-runner:latest
      ignore_errors: true
    - name: run the agent
      command: |
        docker exec -it gitlab-runner /bin/bash -c \
          "gitlab-runner register -n --url https://gitlab.com/ --registration-token GZqpz8aRxUqiY3FsNqAz --executor docker --description '${}' --docker-image 'docker:19.03.1' --docker-volumes /var/run/docker.sock:/var/run/docker.sock --docker-volumes /home/gitlab-runner:/home/gitlab-runner --docker-volumes /builds:/builds --tag-list molecule-workshop"